pipeline:
  name: AWS Security Group Module Integration Test
  identifier: aws_security_group_integration_test
  projectIdentifier: your_project
  orgIdentifier: your_org
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: your_github_connector
        repoName: terraform-aws-security-group
        build: <+input>
  stages:
    - stage:
        name: Terraform Validation and Lint
        identifier: validation_lint
        description: Validate Terraform code and run linting checks
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Terraform Format Check
                  identifier: terraform_fmt
                  spec:
                    connectorRef: account.harnessImage
                    image: hashicorp/terraform:1.6
                    shell: Sh
                    command: |
                      echo "Checking Terraform formatting..."
                      terraform fmt -check -recursive -diff
                  failureStrategies:
                    - onFailure:
                        errors:
                          - AllErrors
                        action:
                          type: MarkAsFailure
              
              - step:
                  type: Run
                  name: Terraform Init
                  identifier: terraform_init
                  spec:
                    connectorRef: account.harnessImage
                    image: hashicorp/terraform:1.6
                    shell: Sh
                    command: |
                      echo "Initializing Terraform..."
                      terraform init -backend=false
              
              - step:
                  type: Run
                  name: Terraform Validate
                  identifier: terraform_validate
                  spec:
                    connectorRef: account.harnessImage
                    image: hashicorp/terraform:1.6
                    shell: Sh
                    command: |
                      echo "Validating Terraform configuration..."
                      terraform validate
              
              - step:
                  type: Run
                  name: TFLint
                  identifier: tflint
                  spec:
                    connectorRef: account.harnessImage
                    image: ghcr.io/terraform-linters/tflint:latest
                    shell: Sh
                    command: |
                      echo "Running TFLint..."
                      tflint --init
                      tflint --format compact
                  failureStrategies:
                    - onFailure:
                        errors:
                          - AllErrors
                        action:
                          type: Ignore
              
              - step:
                  type: Run
                  name: Checkov Security Scan
                  identifier: checkov_scan
                  spec:
                    connectorRef: account.harnessImage
                    image: bridgecrew/checkov:latest
                    shell: Sh
                    command: |
                      echo "Running Checkov security scan..."
                      checkov -d . --framework terraform --soft-fail
                  failureStrategies:
                    - onFailure:
                        errors:
                          - AllErrors
                        action:
                          type: Ignore

    - stage:
        name: Integration Test - Dev
        identifier: integration_test_dev
        description: Run integration tests in Dev environment
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Setup Test Environment
                  identifier: setup_test_env
                  spec:
                    connectorRef: account.harnessImage
                    image: hashicorp/terraform:1.6
                    shell: Sh
                    envVariables:
                      AWS_REGION: <+pipeline.variables.aws_region>
                      AWS_ACCESS_KEY_ID: <+secrets.getValue("aws_access_key_id")>
                      AWS_SECRET_ACCESS_KEY: <+secrets.getValue("aws_secret_access_key")>
                      ENVIRONMENT: dev
                    command: |
                      echo "Setting up test environment..."
                      cd tests/integration
                      
                      # Create tfvars file for testing
                      cat > terraform.tfvars <<EOF
                      vpc_id = "<+pipeline.variables.test_vpc_id>"
                      security_group_name = "test-sg-${DRONE_BUILD_NUMBER}"
                      description = "Integration test security group"
                      
                      ingress_rules = [
                        {
                          from_port   = 443
                          to_port     = 443
                          protocol    = "tcp"
                          cidr_blocks = ["0.0.0.0/0"]
                          description = "HTTPS from anywhere"
                        },
                        {
                          from_port   = 80
                          to_port     = 80
                          protocol    = "tcp"
                          cidr_blocks = ["0.0.0.0/0"]
                          description = "HTTP from anywhere"
                        }
                      ]
                      
                      egress_rules = [
                        {
                          from_port   = 0
                          to_port     = 0
                          protocol    = "-1"
                          cidr_blocks = ["0.0.0.0/0"]
                          description = "Allow all outbound"
                        }
                      ]
                      
                      tags = {
                        Environment = "test"
                        ManagedBy   = "Harness"
                        BuildNumber = "${DRONE_BUILD_NUMBER}"
                      }
                      EOF
                      
                      echo "Test configuration created"
              
              - step:
                  type: Run
                  name: Terraform Init and Plan
                  identifier: terraform_plan
                  spec:
                    connectorRef: account.harnessImage
                    image: hashicorp/terraform:1.6
                    shell: Sh
                    envVariables:
                      AWS_REGION: <+pipeline.variables.aws_region>
                      AWS_ACCESS_KEY_ID: <+secrets.getValue("aws_access_key_id")>
                      AWS_SECRET_ACCESS_KEY: <+secrets.getValue("aws_secret_access_key")>
                    command: |
                      cd tests/integration
                      
                      echo "Initializing Terraform..."
                      terraform init
                      
                      echo "Creating execution plan..."
                      terraform plan -out=tfplan
                      terraform show -json tfplan > plan.json
                      
                      echo "Plan created successfully"
              
              - step:
                  type: Run
                  name: Terraform Apply
                  identifier: terraform_apply
                  spec:
                    connectorRef: account.harnessImage
                    image: hashicorp/terraform:1.6
                    shell: Sh
                    envVariables:
                      AWS_REGION: <+pipeline.variables.aws_region>
                      AWS_ACCESS_KEY_ID: <+secrets.getValue("aws_access_key_id")>
                      AWS_SECRET_ACCESS_KEY: <+secrets.getValue("aws_secret_access_key")>
                    command: |
                      cd tests/integration
                      
                      echo "Applying Terraform configuration..."
                      terraform apply -auto-approve tfplan
                      
                      echo "Saving outputs..."
                      terraform output -json > outputs.json
                      
                      # Export security group ID for testing
                      export SG_ID=$(terraform output -raw security_group_id)
                      echo "Security Group ID: $SG_ID"
              
              - step:
                  type: Run
                  name: Run Integration Tests
                  identifier: run_tests
                  spec:
                    connectorRef: account.harnessImage
                    image: python:3.11-slim
                    shell: Sh
                    envVariables:
                      AWS_REGION: <+pipeline.variables.aws_region>
                      AWS_ACCESS_KEY_ID: <+secrets.getValue("aws_access_key_id")>
                      AWS_SECRET_ACCESS_KEY: <+secrets.getValue("aws_secret_access_key")>
                    command: |
                      cd tests/integration
                      
                      echo "Installing dependencies..."
                      pip install boto3 pytest pytest-json-report --quiet
                      
                      # Get security group ID from Terraform outputs
                      export SG_ID=$(cat outputs.json | python -c "import sys, json; print(json.load(sys.stdin)['security_group_id']['value'])")
                      echo "Testing Security Group: $SG_ID"
                      
                      # Create test script
                      cat > test_security_group.py <<'PYTEST'
                      import boto3
                      import os
                      import pytest
                      
                      @pytest.fixture
                      def ec2_client():
                          return boto3.client('ec2', region_name=os.environ['AWS_REGION'])
                      
                      @pytest.fixture
                      def sg_id():
                          return os.environ['SG_ID']
                      
                      def test_security_group_exists(ec2_client, sg_id):
                          """Test that security group exists"""
                          response = ec2_client.describe_security_groups(GroupIds=[sg_id])
                          assert len(response['SecurityGroups']) == 1
                          print(f"✓ Security group {sg_id} exists")
                      
                      def test_security_group_name(ec2_client, sg_id):
                          """Test security group name"""
                          response = ec2_client.describe_security_groups(GroupIds=[sg_id])
                          sg = response['SecurityGroups'][0]
                          assert 'test-sg-' in sg['GroupName']
                          print(f"✓ Security group name is valid: {sg['GroupName']}")
                      
                      def test_ingress_rules(ec2_client, sg_id):
                          """Test ingress rules are configured correctly"""
                          response = ec2_client.describe_security_groups(GroupIds=[sg_id])
                          sg = response['SecurityGroups'][0]
                          
                          ingress_rules = sg['IpPermissions']
                          assert len(ingress_rules) >= 2, "Should have at least 2 ingress rules"
                          
                          # Check for HTTPS rule
                          https_rule = [r for r in ingress_rules if r.get('FromPort') == 443]
                          assert len(https_rule) > 0, "HTTPS rule should exist"
                          print(f"✓ Found {len(ingress_rules)} ingress rules")
                      
                      def test_egress_rules(ec2_client, sg_id):
                          """Test egress rules allow all outbound"""
                          response = ec2_client.describe_security_groups(GroupIds=[sg_id])
                          sg = response['SecurityGroups'][0]
                          
                          egress_rules = sg['IpPermissionsEgress']
                          assert len(egress_rules) > 0, "Should have egress rules"
                          print(f"✓ Found {len(egress_rules)} egress rules")
                      
                      def test_tags(ec2_client, sg_id):
                          """Test that required tags are present"""
                          response = ec2_client.describe_security_groups(GroupIds=[sg_id])
                          sg = response['SecurityGroups'][0]
                          
                          tags = {tag['Key']: tag['Value'] for tag in sg.get('Tags', [])}
                          assert 'Environment' in tags, "Environment tag should exist"
                          assert 'ManagedBy' in tags, "ManagedBy tag should exist"
                          assert tags['ManagedBy'] == 'Harness'
                          print(f"✓ All required tags present: {list(tags.keys())}")
                      PYTEST
                      
                      echo "Running integration tests..."
                      pytest test_security_group.py -v --json-report --json-report-file=report.json
                      
                      echo "Test Results:"
                      cat report.json | python -c "import sys, json; report = json.load(sys.stdin); print(f\"Tests: {report['summary']['total']}, Passed: {report['summary'].get('passed', 0)}, Failed: {report['summary'].get('failed', 0)}\")"
              
              - step:
                  type: Run
                  name: Terraform Destroy
                  identifier: terraform_destroy
                  spec:
                    connectorRef: account.harnessImage
                    image: hashicorp/terraform:1.6
                    shell: Sh
                    envVariables:
                      AWS_REGION: <+pipeline.variables.aws_region>
                      AWS_ACCESS_KEY_ID: <+secrets.getValue("aws_access_key_id")>
                      AWS_SECRET_ACCESS_KEY: <+secrets.getValue("aws_secret_access_key")>
                    command: |
                      cd tests/integration
                      
                      echo "Cleaning up test resources..."
                      terraform destroy -auto-approve
                      
                      echo "Test environment cleaned up successfully"
                  when:
                    stageStatus: All
                  failureStrategies:
                    - onFailure:
                        errors:
                          - AllErrors
                        action:
                          type: Ignore

    - stage:
        name: Integration Test - Staging
        identifier: integration_test_staging
        description: Run integration tests in Staging environment
        type: CI
        when:
          pipelineStatus: Success
          condition: <+pipeline.variables.run_staging_tests> == "true"
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run Staging Tests
                  identifier: staging_tests
                  spec:
                    connectorRef: account.harnessImage
                    image: hashicorp/terraform:1.6
                    shell: Sh
                    envVariables:
                      AWS_REGION: <+pipeline.variables.aws_region>
                      AWS_ACCESS_KEY_ID: <+secrets.getValue("aws_access_key_id_staging")>
                      AWS_SECRET_ACCESS_KEY: <+secrets.getValue("aws_secret_access_key_staging")>
                      ENVIRONMENT: staging
                    command: |
                      echo "Running staging environment tests..."
                      # Similar steps as dev environment
                      echo "Staging tests completed"

  variables:
    - name: aws_region
      type: String
      description: AWS Region for testing
      required: true
      value: us-east-1
    - name: test_vpc_id
      type: String
      description: VPC ID for testing security groups
      required: true
      value: <+input>
    - name: run_staging_tests
      type: String
      description: Run staging environment tests
      required: false
      value: "false"
  notificationRules:
    - name: Pipeline Failure Notification
      identifier: failure_notification
      pipelineEvents:
        - type: PipelineFailed
      notificationMethod:
        type: Email
        spec:
          userGroups:
            - account._account_all_users
          recipients:
            - devops-team@company.com
      enabled: true
